# Generated by Django 4.2.3 on 2023-09-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_login_details_alter_rest_details_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Menu_name', models.CharField(max_length=25)),
                ('Menu_desc', models.CharField(max_length=50)),
                ('Menu_Price', models.IntegerField()),
                ('Menu_img', models.ImageField(upload_to='media/')),
                ('Rest_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurant.rest_details')),
            ],
        ),
    ]
